#define MAP_ATT_BuildErrorRsp                              0xac1
#define MAP_ATT_BuildExchangeMTURsp                        0xacd
#define MAP_ATT_BuildFindByTypeValueRsp                    0xae5
#define MAP_ATT_BuildFindInfoRsp                           0xad9
#define MAP_ATT_BuildHandleValueInd                        0xb39
#define MAP_ATT_BuildPrepareWriteRsp                       0xb2d
#define MAP_ATT_BuildReadBlobRsp                           0xb0f
#define MAP_ATT_BuildReadByGrpTypeRsp                      0xb21
#define MAP_ATT_BuildReadByTypeRsp                         0xaf1
#define MAP_ATT_BuildReadMultiRsp                          0xb1b
#define MAP_ATT_BuildReadRsp                               0xafd
#define MAP_ATT_CompareUUID                                0xb45
#define MAP_ATT_ConvertUUIDto128                           0xb4b
#define MAP_ATT_ErrorRsp                                   0xa67
#define MAP_ATT_ExchangeMTURsp                             0xa6d
#define MAP_ATT_ExecuteWriteRsp                            0xaa9
#define MAP_ATT_FindByTypeValueRsp                         0xa79
#define MAP_ATT_FindInfoRsp                                0xa73
#define MAP_ATT_HandleValueInd                             0xab5
#define MAP_ATT_HandleValueNoti                            0xaaf
#define MAP_ATT_ParseExchangeMTUReq                        0xac7
#define MAP_ATT_ParseExecuteWriteReq                       0xb33
#define MAP_ATT_ParseFindByTypeValueReq                    0xadf
#define MAP_ATT_ParseFindInfoReq                           0xad3
#define MAP_ATT_ParsePacket                                0xabb
#define MAP_ATT_ParsePrepareWriteReq                       0xb27
#define MAP_ATT_ParseReadBlobReq                           0xb09
#define MAP_ATT_ParseReadByTypeReq                         0xaeb
#define MAP_ATT_ParseReadMultiReq                          0xb15
#define MAP_ATT_ParseReadReq                               0xaf7
#define MAP_ATT_ParseWriteReq                              0xb03
#define MAP_ATT_PrepareWriteRsp                            0xaa3
#define MAP_ATT_ReadBlobRsp                                0xa8b
#define MAP_ATT_ReadByGrpTypeRsp                           0xa97
#define MAP_ATT_ReadByTypeRsp                              0xa7f
#define MAP_ATT_ReadMultiRsp                               0xa91
#define MAP_ATT_ReadRsp                                    0xa85
#define MAP_ATT_WriteRsp                                   0xa9d
#define MAP_Accel_AddService                               0x773
#define MAP_Accel_GetParameter                             0x785
#define MAP_Accel_RegisterAppCBs                           0x779
#define MAP_Accel_SetParameter                             0x77f
#define MAP_Batt_AddService                                0x79d
#define MAP_Batt_Register                                  0x7a3
#define MAP_CodeGeneratorStartPoint                        0xa37
#define MAP_CodeGenerator_EVT_1_CB                         0xa1f
#define MAP_CodeGenerator_EVT_2_CB                         0xa25
#define MAP_CodeGenerator_EVT_3_CB                         0xa2b
#define MAP_CodeGenerator_EVT_4_CB                         0xa31
#define MAP_DevInfo_AddService                             0x7bb
#define MAP_DevInfo_SetParameter                           0x7c1
#define MAP_EcoExecProfileChangeCB                         0xa01
#define MAP_EcoExecProfile_AddService                      0x647
#define MAP_EcoExecProfile_GetParameter                    0x653
#define MAP_EcoExecProfile_HandleConnStatusCB              0x665
#define MAP_EcoExecProfile_ReadAttrCB                      0x659
#define MAP_EcoExecProfile_RegisterAppCBs                  0x64d
#define MAP_EcoExecProfile_WriteAttrCB                     0x65f
#define MAP_GAPBondMgr_Init                                0x887
#define MAP_GAPBondMgr_LinkEst                             0x81b
#define MAP_GAPBondMgr_ProcessEvent                        0x88d
#define MAP_GAPBondMgr_ProcessGAPMsg                       0x839
#define MAP_GAPBondMgr_Register                            0x833
#define MAP_GAPBondMgr_ResolveAddr                         0x821
#define MAP_GAPBondMgr_ServiceChangeInd                    0x827
#define MAP_GAPBondMgr_SetParameter                        0x815
#define MAP_GAPBondMgr_UpdateCharCfg                       0x82d
#define MAP_GAPRole_GetParameter                           0x9c5
#define MAP_GAPRole_Init                                   0x9d7
#define MAP_GAPRole_ProcessEvent                           0x9dd
#define MAP_GAPRole_SendUpdateParam                        0x9e9
#define MAP_GAPRole_SetParameter                           0x9bf
#define MAP_GAPRole_StartDevice                            0x9cb
#define MAP_GAPRole_TerminateConnection                    0x9d1
#define MAP_GAP_Authenticate                               0xbe1
#define MAP_GAP_Bond                                       0xbf3
#define MAP_GAP_DeviceInit                                 0x80f
#define MAP_GAP_EndDiscoverable                            0xc59
#define MAP_GAP_GetParamValue                              0xb57
#define MAP_GAP_Init                                       0xca7
#define MAP_GAP_MakeDiscoverable                           0xc4d
#define MAP_GAP_NumActiveConnections                       0xcb3
#define MAP_GAP_ParamsInit                                 0xb5d
#define MAP_GAP_PasscodeUpdate                             0xbed
#define MAP_GAP_PeriDevMgrInit                             0xc5f
#define MAP_GAP_ProcessEvent                               0xcad
#define MAP_GAP_RegisterForHCIMsgs                         0xca1
#define MAP_GAP_ResolvePrivateAddr                         0xbbd
#define MAP_GAP_SecParamsInit                              0xb63
#define MAP_GAP_SendSlaveSecurityRequest                   0xc9b
#define MAP_GAP_SetParamValue                              0xb51
#define MAP_GAP_Signable                                   0xbdb
#define MAP_GAP_TerminateAuth                              0xbe7
#define MAP_GAP_TerminateLinkReq                           0xbd5
#define MAP_GAP_UpdateAdvertisingData                      0xc53
#define MAP_GATTServApp_AddService                         0xdd9
#define MAP_GATTServApp_FindAttr                           0xdd3
#define MAP_GATTServApp_Init                               0xdbb
#define MAP_GATTServApp_InitCharCfg                        0xe45
#define MAP_GATTServApp_ProcessCCCWriteReq                 0xe57
#define MAP_GATTServApp_ProcessCharCfg                     0xe5d
#define MAP_GATTServApp_ProcessEvent                       0xdc1
#define MAP_GATTServApp_ReadAttr                           0xe2d
#define MAP_GATTServApp_ReadCharCfg                        0xe4b
#define MAP_GATTServApp_RegisterForMsg                     0xdb5
#define MAP_GATTServApp_RegisterService                    0xdc7
#define MAP_GATTServApp_SendCCCUpdatedEvent                0xe69
#define MAP_GATTServApp_SendServiceChangedInd              0xe3f
#define MAP_GATTServApp_UpdateCharCfg                      0xe39
#define MAP_GATTServApp_WriteAttr                          0xe33
#define MAP_GATTServApp_WriteCharCfg                       0xe51
#define MAP_GATT_FindHandle                                0xd13
#define MAP_GATT_FindHandleUUID                            0xd0d
#define MAP_GATT_FindNextAttr                              0xd19
#define MAP_GATT_Indication                                0xd25
#define MAP_GATT_Init                                      0xd91
#define MAP_GATT_InitServer                                0xce9
#define MAP_GATT_Notification                              0xd2b
#define MAP_GATT_ProcessEvent                              0xd97
#define MAP_GATT_RegisterForReq                            0xcf5
#define MAP_GATT_RegisterService                           0xcef
#define MAP_GATT_ServiceChangedInd                         0xd07
#define MAP_GATT_ServiceNumAttrs                           0xd1f
#define MAP_GATT_VerifyReadPermissions                     0xcfb
#define MAP_GATT_VerifyWritePermissions                    0xd01
#define MAP_GGS_AddService                                 0xcd1
#define MAP_GGS_SetParameter                               0xccb
#define MAP_HCI_CommandCompleteEvent                       0xf29
#define MAP_HCI_CommandStatusEvent                         0xf35
#define MAP_HCI_DataBufferOverflowEvent                    0xf1d
#define MAP_HCI_DisconnectCmd                              0xe7b
#define MAP_HCI_EXT_ClkDivOnHaltCmd                        0xecf
#define MAP_HCI_EXT_DeclareNvUsageCmd                      0xed5
#define MAP_HCI_GAPTaskRegister                            0x1631
#define MAP_HCI_Init                                       0x1625
#define MAP_HCI_L2CAPTaskRegister                          0x1637
#define MAP_HCI_LE_AddWhiteListCmd                         0xeb7
#define MAP_HCI_LE_ClearWhiteListCmd                       0xeb1
#define MAP_HCI_LE_LtkReqNegReplyCmd                       0xec9
#define MAP_HCI_LE_LtkReqReplyCmd                          0xec3
#define MAP_HCI_LE_RandCmd                                 0xebd
#define MAP_HCI_LE_ReadBufSizeCmd                          0xe8d
#define MAP_HCI_LE_SetAdvDataCmd                           0xe9f
#define MAP_HCI_LE_SetAdvEnableCmd                         0xeab
#define MAP_HCI_LE_SetAdvParamCmd                          0xe99
#define MAP_HCI_LE_SetRandomAddressCmd                     0xe93
#define MAP_HCI_LE_SetScanRspDataCmd                       0xea5
#define MAP_HCI_NumOfCompletedPacketsEvent                 0xf23
#define MAP_HCI_ProcessEvent                               0x162b
#define MAP_HCI_ReadBDADDRCmd                              0xe81
#define MAP_HCI_ReadRssiCmd                                0xe87
#define MAP_HCI_SMPTaskRegister                            0x163d
#define MAP_HCI_SendCommandCompleteEvent                   0xf41
#define MAP_HCI_SendCommandStatusEvent                     0xf3b
#define MAP_HCI_SendControllerToHostEvent                  0xf47
#define MAP_HCI_SendDataPkt                                0xe75
#define MAP_HCI_TxDataBufferInsert                         0xef3
#define MAP_HCI_TxDataSend                                 0xef9
#define MAP_HCI_VendorSpecifcCommandCompleteEvent          0xf2f
#define MAP_HCI_bm_alloc                                   0xe6f
#define MAP_HalAdcInit                                     0x8b7
#define MAP_HalAdcRead                                     0x8bd
#define MAP_HalAdcSetReference                             0x8c3
#define MAP_HalAesInit                                     0x8cf
#define MAP_HalDmaInit                                     0x8d5
#define MAP_HalDriverInit                                  0x8e1
#define MAP_HalFlashErase                                  0x8ff
#define MAP_HalFlashRead                                   0x8f3
#define MAP_HalFlashWrite                                  0x8f9
#define MAP_HalKeyConfig                                   0x90b
#define MAP_HalKeyInit                                     0x905
#define MAP_HalKeyPoll                                     0x911
#define MAP_HalLedBlink                                    0x92f
#define MAP_HalLedInit                                     0x923
#define MAP_HalLedOnOff                                    0x93b
#define MAP_HalLedSet                                      0x929
#define MAP_HalLedUpdate                                   0x935
#define MAP_Hal_Init                                       0x8db
#define MAP_Hal_ProcessEvent                               0x8e7
#define MAP_Hal_ProcessPoll                                0x8ed
#define MAP_InitBoard                                      0x75b
#define MAP_L2CAP_BuildCmdReject                           0xfd1
#define MAP_L2CAP_CmdReject                                0xf83
#define MAP_L2CAP_ConnParamUpdateReq                       0xf89
#define MAP_L2CAP_Init                                     0xf8f
#define MAP_L2CAP_ParseParamUpdateReq                      0xfe3
#define MAP_L2CAP_ProcessEvent                             0xf95
#define MAP_L2CAP_RegisterApp                              0xf77
#define MAP_L2CAP_SendData                                 0xf7d
#define MAP_L2CAP_bm_alloc                                 0x101f
#define MAP_LL_AddWhiteListDevice                          0x108b
#define MAP_LL_ClearWhiteList                              0x1085
#define MAP_LL_ConnActive                                  0x10df
#define MAP_LL_ConnParamUpdateCback                        0xf59
#define MAP_LL_ConnectionCompleteCback                     0xf4d
#define MAP_LL_CtrlToHostFlowControl                       0x10a3
#define MAP_LL_Disconnect                                  0x10af
#define MAP_LL_DisconnectCback                             0xf53
#define MAP_LL_ENC_AES128_Encrypt                          0x1247
#define MAP_LL_ENC_Decrypt                                 0x1295
#define MAP_LL_ENC_DecryptMsg                              0x1283
#define MAP_LL_ENC_Encrypt                                 0x128f
#define MAP_LL_ENC_EncryptMsg                              0x127d
#define MAP_LL_ENC_GenDeviceIV                             0x123b
#define MAP_LL_ENC_GenDeviceSKD                            0x1235
#define MAP_LL_ENC_GenerateMIC                             0x1289
#define MAP_LL_ENC_GenerateNonce                           0x1241
#define MAP_LL_ENC_GeneratePseudoRandNum                   0x1229
#define MAP_LL_ENC_GenerateTrueRandNum                     0x122f
#define MAP_LL_ENC_InitAesDMA                              0x124d
#define MAP_LL_ENC_InitDMA0                                0x1253
#define MAP_LL_ENC_LoadEmptyIV                             0x1271
#define MAP_LL_ENC_LoadKey                                 0x1277
#define MAP_LL_ENC_MoveData                                0x1259
#define MAP_LL_ENC_ReverseBytes                            0x1223
#define MAP_LL_ENC_SetupCryptoDMA                          0x1265
#define MAP_LL_ENC_SetupLoadDMA                            0x125f
#define MAP_LL_ENC_StartAES                                0x126b
#define MAP_LL_EXT_ClkDivOnHalt                            0x10e5
#define MAP_LL_EXT_DeclareNvUsage                          0x10eb
#define MAP_LL_EXT_ExtendRfRangeCback                      0xeed
#define MAP_LL_EXT_SetRxGainCback                          0xee1
#define MAP_LL_EXT_SetTxPowerCback                         0xee7
#define MAP_LL_EncChangeCback                              0xf6b
#define MAP_LL_EncKeyRefreshCback                          0xf71
#define MAP_LL_EncLtkNegReply                              0x10d9
#define MAP_LL_EncLtkReply                                 0x10d3
#define MAP_LL_EncLtkReqCback                              0xf65
#define MAP_LL_Encrypt                                     0x1091
#define MAP_LL_Init                                        0x1067
#define MAP_LL_ProcessEvent                                0x106d
#define MAP_LL_PseudoRand                                  0x109d
#define MAP_LL_Rand                                        0x1097
#define MAP_LL_RandCback                                   0xedb
#define MAP_LL_ReadBDADDR                                  0x1079
#define MAP_LL_ReadRemoteVersionInfoCback                  0xf5f
#define MAP_LL_ReadRssi                                    0x10a9
#define MAP_LL_Reset                                       0x1073
#define MAP_LL_RxDataCompleteCback                         0xf0b
#define MAP_LL_RxReqDataBufCback                           0xf05
#define MAP_LL_SetAdvControl                               0x10c7
#define MAP_LL_SetAdvData                                  0x10c1
#define MAP_LL_SetAdvParam                                 0x10bb
#define MAP_LL_SetRandomAddress                            0x107f
#define MAP_LL_SetScanRspData                              0x10cd
#define MAP_LL_TxData                                      0x10b5
#define MAP_LL_TxDataCompleteCback                         0xf11
#define MAP_OnBoard_KeyCallback                            0x76d
#define MAP_OnBoard_SendKeys                               0x767
#define MAP_Onboard_rand                                   0x761
#define MAP_PHY_AddWlEntry                                 0x13f7
#define MAP_PHY_ClearAllRegsAndFifos                       0x13a9
#define MAP_PHY_ClearBlacklist                             0x140f
#define MAP_PHY_ClearBlacklistIndex                        0x1409
#define MAP_PHY_ClearSavedWhiteList                        0x1415
#define MAP_PHY_ClearWhitelist                             0x13f1
#define MAP_PHY_CommitRxFifo                               0x143f
#define MAP_PHY_ConfigWhitener                             0x142d
#define MAP_PHY_ConfigureAppendRfStatus                    0x1421
#define MAP_PHY_ConfigureFifoDataProcessing                0x141b
#define MAP_PHY_ConfigureMD                                0x13d3
#define MAP_PHY_DeallocateRxFifo                           0x1445
#define MAP_PHY_GetAdvChans                                0x13c1
#define MAP_PHY_GetEndCause                                0x13d9
#define MAP_PHY_Init                                       0x1391
#define MAP_PHY_InitSeqStat                                0x13df
#define MAP_PHY_LoadNR                                     0x139d
#define MAP_PHY_Reset                                      0x1397
#define MAP_PHY_RetryRxFifo                                0x1439
#define MAP_PHY_RetryTxFifo                                0x1433
#define MAP_PHY_SetAdvChans                                0x13c7
#define MAP_PHY_SetAdvWlPolicy                             0x13fd
#define MAP_PHY_SetBlacklistIndex                          0x1403
#define MAP_PHY_SetCRCInit                                 0x13bb
#define MAP_PHY_SetEndConnection                           0x13cd
#define MAP_PHY_SetFifoConfig                              0x1427
#define MAP_PHY_SetMaxNack                                 0x13eb
#define MAP_PHY_SetOwnAddr                                 0x13af
#define MAP_PHY_SetPeerAddr                                0x13b5
#define MAP_PHY_SetRfFreq                                  0x144b
#define MAP_PHY_SetSyncWord                                0x13e5
#define MAP_PHY_VerifyNR                                   0x13a3
#define MAP_SM_CalcRandomAddr                              0x1457
#define MAP_SM_GenerateAuthenSig                           0x1463
#define MAP_SM_Init                                        0x1589
#define MAP_SM_PasskeyUpdate                               0x14cf
#define MAP_SM_ProcessEvent                                0x158f
#define MAP_SM_ResolveRandomAddrs                          0x145d
#define MAP_SM_ResponderInit                               0x155f
#define MAP_SM_StartPairing                                0x14c9
#define MAP_SM_VerifyAuthenSig                             0x1469
#define MAP_SimpleBLEPeripheral_Init                       0x9ef
#define MAP_SimpleBLEPeripheral_ProcessEvent               0x9f5
#define MAP_SimpleProfile_AddService                       0xa3d
#define MAP_SimpleProfile_GetParameter                     0xa4f
#define MAP_SimpleProfile_RegisterAppCBs                   0xa43
#define MAP_SimpleProfile_SetParameter                     0xa49
#define MAP_accInit                                        0x7cd
#define MAP_accReadAcc                                     0x7df
#define MAP_accReadReg                                     0x7d9
#define MAP_accSetFreeFallEvent                            0x7e5
#define MAP_accWriteReg                                    0x7d3
#define MAP_accelEnablerChangeCB                           0xa13
#define MAP_accelRead                                      0xa07
#define MAP_accel_HandleConnStatusCB                       0x797
#define MAP_accel_ReadAttrCB                               0x78b
#define MAP_accel_WriteAttrCB                              0x791
#define MAP_aesDmaInit                                     0x8c9
#define MAP_attSendMsg                                     0xb3f
#define MAP_battMeasure                                    0x7b5
#define MAP_battProfileChangeCB                            0xa19
#define MAP_battReadAttrCB                                 0x7a9
#define MAP_battWriteAttrCB                                0x7af
#define MAP_bm_desc_from_payload                           0x953
#define MAP_cleanErasedPage                                0x983
#define MAP_compactPage                                    0x99b
#define MAP_devInfo_ReadAttrCB                             0x7c7
#define MAP_disconnectNext                                 0xc1d
#define MAP_erasePage                                      0x97d
#define MAP_findItem                                       0x98f
#define MAP_findOffset                                     0x989
#define MAP_gapAddAddrAdj                                  0xb7b
#define MAP_gapBondMgrAddBond                              0x857
#define MAP_gapBondMgrAuthenticate                         0x89f
#define MAP_gapBondMgrBondReq                              0x8a5
#define MAP_gapBondMgrBondTotal                            0x875
#define MAP_gapBondMgrChangeState                          0x83f
#define MAP_gapBondMgrEraseAllBondings                     0x87b
#define MAP_gapBondMgrEraseBonding                         0x881
#define MAP_gapBondMgrFindAddr                             0x863
#define MAP_gapBondMgrFindCharCfgItem                      0x84b
#define MAP_gapBondMgrGetPublicAddr                        0x85d
#define MAP_gapBondMgrInvertCharCfgItem                    0x851
#define MAP_gapBondMgrReadBonds                            0x86f
#define MAP_gapBondMgrResolvePrivateAddr                   0x869
#define MAP_gapBondMgrSendServiceChange                    0x893
#define MAP_gapBondMgrUpdateCharCfg                        0x845
#define MAP_gapBondMgr_SyncCharCfg                         0x8b1
#define MAP_gapBondMgr_SyncWhiteList                       0x8ab
#define MAP_gapBondSetupPrivFlag                           0x899
#define MAP_gapDetermineAddrType                           0xb81
#define MAP_gapFindADType                                  0xbcf
#define MAP_gapFreeAdvertState                             0xc8f
#define MAP_gapFreeAuthLink                                0xc29
#define MAP_gapFreeEstLink                                 0xc2f
#define MAP_gapGetDevAddress                               0xbab
#define MAP_gapGetDevAddressMode                           0xba5
#define MAP_gapGetIRK                                      0xbb1
#define MAP_gapGetSRK                                      0xb8d
#define MAP_gapGetSignCounter                              0xb93
#define MAP_gapIncSignCounter                              0xb99
#define MAP_gapIsAdvertising                               0xbc3
#define MAP_gapPairingCompleteCB                           0xc47
#define MAP_gapPasskeyNeededCB                             0xc41
#define MAP_gapPeriProcessHCICmdCompleteEvt                0xc65
#define MAP_gapProcessAdvertisingEvt                       0xc83
#define MAP_gapProcessConnUpdateCompleteEvt                0xbff
#define MAP_gapProcessConnectionCompleteEvt                0xbf9
#define MAP_gapProcessDisconnectCompleteEvt                0xc05
#define MAP_gapProcessHCICmdCompleteEvt                    0xcbf
#define MAP_gapProcessNewAddr                              0xb75
#define MAP_gapProcessOSALMsg                              0xcb9
#define MAP_gapProcessRandomAddrComplete                   0xb87
#define MAP_gapReadBD_ADDRStatus                           0xb69
#define MAP_gapReadBufSizeCmdStatus                        0xb6f
#define MAP_gapRegisterPeripheral                          0xcc5
#define MAP_gapRole_ProcessGAPMsg                          0x9e3
#define MAP_gapSendBondCompleteEvent                       0xc35
#define MAP_gapSendDeviceInitDoneEvent                     0xbb7
#define MAP_gapSendLinkUpdateEvent                         0xc17
#define MAP_gapSendMakeDiscEvent                           0xc89
#define MAP_gapSendPairingReqEvent                         0xc3b
#define MAP_gapSetAdvParams                                0xc6b
#define MAP_gapSetAdvParamsStatus                          0xc71
#define MAP_gapUpdateConnSignCounter                       0xb9f
#define MAP_gapValidADType                                 0xbc9
#define MAP_gapWriteAdvDataStatus                          0xc7d
#define MAP_gapWriteAdvEnableStatus                        0xc77
#define MAP_gattFindServerInfo                             0xd79
#define MAP_gattGetServerStatus                            0xd73
#define MAP_gattNotifyEvent                                0xda3
#define MAP_gattProcessExchangeMTUReq                      0xd3d
#define MAP_gattProcessExecuteWriteReq                     0xd6d
#define MAP_gattProcessFindByTypeValueReq                  0xd49
#define MAP_gattProcessFindInfoReq                         0xd43
#define MAP_gattProcessReadByGrpTypeReq                    0xd61
#define MAP_gattProcessReadByTypeReq                       0xd4f
#define MAP_gattProcessReadMultiReq                        0xd5b
#define MAP_gattProcessReadReq                             0xd55
#define MAP_gattProcessRxData                              0xd9d
#define MAP_gattProcessWriteReq                            0xd67
#define MAP_gattRegisterServer                             0xd8b
#define MAP_gattServApp_FindAuthorizeAttrCB                0xe21
#define MAP_gattServApp_FindCharCfgItem                    0xe1b
#define MAP_gattServApp_FindPrepareWriteQ                  0xe15
#define MAP_gattServApp_FindServiceCBs                     0xddf
#define MAP_gattServApp_HandleConnStatusCB                 0xe63
#define MAP_gattServApp_ProcessExecuteWriteReq             0xe0f
#define MAP_gattServApp_ProcessFindByTypeValueReq          0xdeb
#define MAP_gattServApp_ProcessMsg                         0xde5
#define MAP_gattServApp_ProcessPrepareWriteReq             0xe09
#define MAP_gattServApp_ProcessReadByGrpTypeReq            0xdfd
#define MAP_gattServApp_ProcessReadByTypeReq               0xdf1
#define MAP_gattServApp_ProcessReadMultiReq                0xdf7
#define MAP_gattServApp_ProcessWriteReq                    0xe03
#define MAP_gattServApp_SetNumPrepareWrites                0xdcd
#define MAP_gattServApp_WriteAttrCB                        0xe27
#define MAP_gattServerHandleConnStatusCB                   0xd85
#define MAP_gattServerHandleTimerCB                        0xd7f
#define MAP_gattServerProcessMsgCB                         0xd37
#define MAP_gattServiceLastHandle                          0xd31
#define MAP_gattStartTimer                                 0xda9
#define MAP_gattStopTimer                                  0xdaf
#define MAP_generate_subkey                                0x14b7
#define MAP_ggs_ReadAttrCB                                 0xcdd
#define MAP_ggs_SetAttrWPermit                             0xcd7
#define MAP_ggs_WriteAttrCB                                0xce3
#define MAP_halGetJoyKeyInput                              0x917
#define MAP_halProcessAlarmInterrupt                       0x63b
#define MAP_halProcessFreeFallInterrupt                    0x641
#define MAP_halProcessKeyInterrupt                         0x91d
#define MAP_hciInitEventMasks                              0xf17
#define MAP_hciTxDataBufferReset                           0xeff
#define MAP_initNV                                         0x971
#define MAP_isLimitedDiscoverableMode                      0xc95
#define MAP_l2capAllocChannel                              0xffb
#define MAP_l2capBuildParamUpdateReq                       0xfdd
#define MAP_l2capEncapSendData                             0xfc5
#define MAP_l2capFindLocalId                               0x1007
#define MAP_l2capFreeChannel                               0x1001
#define MAP_l2capHandleRxError                             0x1019
#define MAP_l2capHandleTimerCB                             0x1013
#define MAP_l2capNotifyData                                0xfef
#define MAP_l2capNotifySignal                              0xff5
#define MAP_l2capParseCmdReject                            0xfd7
#define MAP_l2capParsePacket                               0xfcb
#define MAP_l2capParseParamUpdateRsp                       0xfe9
#define MAP_l2capParseSignalHdr                            0xfb3
#define MAP_l2capProcessReq                                0xfad
#define MAP_l2capProcessRsp                                0xfa7
#define MAP_l2capProcessRxData                             0xf9b
#define MAP_l2capProcessSignal                             0xfa1
#define MAP_l2capSendCmd                                   0xfbf
#define MAP_l2capSendReq                                   0xfb9
#define MAP_l2capStopTimer                                 0x100d
#define MAP_leftshift_onebit                               0x14c3
#define MAP_linkDB_Add                                     0x1031
#define MAP_linkDB_Authen                                  0x1055
#define MAP_linkDB_Find                                    0x103d
#define MAP_linkDB_FindFirst                               0x1043
#define MAP_linkDB_Init                                    0x1025
#define MAP_linkDB_NumActive                               0x104f
#define MAP_linkDB_PerformFunc                             0x105b
#define MAP_linkDB_Register                                0x102b
#define MAP_linkDB_Remove                                  0x1037
#define MAP_linkDB_State                                   0x1049
#define MAP_llAdjustForMissedEvent                         0x1205
#define MAP_llAdvEvt_TaskAbort                             0x110f
#define MAP_llAdvEvt_TaskConnect                           0x10f7
#define MAP_llAllocConnId                                  0x11cf
#define MAP_llAllocTask                                    0x12bf
#define MAP_llCheckForLstoDuringSL                         0x1331
#define MAP_llClearRfInts                                  0x112d
#define MAP_llClearSetInts                                 0x1121
#define MAP_llConnCleanup                                  0x11e7
#define MAP_llConnTerminate                                0x11ed
#define MAP_llConvertCtrlProcTimeoutToEvent                0x11ff
#define MAP_llConvertLstoToEvent                           0x11f9
#define MAP_llDequeueCtrlPkt                               0x11bd
#define MAP_llDirectedAdvEvt_TaskEndOk                     0x10f1
#define MAP_llDisableRfInts                                0x1127
#define MAP_llDisableT2E1                                  0x1373
#define MAP_llDisableT2Ints                                0x1367
#define MAP_llDisableT2IntsEvts                            0x136d
#define MAP_llDiscoverableAdvEvt_TaskEndOk                 0x1103
#define MAP_llEnableRfInts                                 0x1133
#define MAP_llEnqueueCtrlPkt                               0x11b7
#define MAP_llExtendRfRange                                0x1151
#define MAP_llFindNextSecTask                              0x12b9
#define MAP_llFindStartType                                0x12b3
#define MAP_llFindTxPowerSettings                          0x114b
#define MAP_llFreeTask                                     0x12c5
#define MAP_llGetActiveTasks                               0x12d7
#define MAP_llGetCurrentFineTime                           0x1385
#define MAP_llGetCurrentTask                               0x12cb
#define MAP_llGetCurrentTime                               0x137f
#define MAP_llGetNextConn                                  0x11e1
#define MAP_llGetNumTasks                                  0x12e3
#define MAP_llGetTask                                      0x12dd
#define MAP_llGetTaskState                                 0x12d1
#define MAP_llGetTimer2Capture                             0x1379
#define MAP_llInitFeatureSet                               0x11f3
#define MAP_llInitTimer2                                   0x1337
#define MAP_llMemCopyDst                                   0x121d
#define MAP_llMemCopySrc                                   0x1217
#define MAP_llNonConnAdvEvt_TaskEndOk                      0x1109
#define MAP_llProcessChanMap                               0x11c9
#define MAP_llProcessPendingTxData                         0x120b
#define MAP_llProcessPostRfOps                             0x1139
#define MAP_llProcessSlaveControlProcedures                0x132b
#define MAP_llReleaseAllConnId                             0x11db
#define MAP_llReleaseConnId                                0x11d5
#define MAP_llReplaceCtrlPkt                               0x11c3
#define MAP_llRestoreConnState                             0x1313
#define MAP_llRestoreRfRegs                                0x1307
#define MAP_llRestore_rxFIFO                               0x12fb
#define MAP_llRestore_txFIFO                               0x12f5
#define MAP_llRfInit                                       0x1115
#define MAP_llSaveConnState                                0x130d
#define MAP_llSaveRfRegs                                   0x1301
#define MAP_llSave_rxFIFO                                  0x12ef
#define MAP_llSave_txFIFO                                  0x12e9
#define MAP_llScheduleTask                                 0x12ad
#define MAP_llScheduler                                    0x12a7
#define MAP_llSchedulerInit                                0x12a1
#define MAP_llSetFreqTune                                  0x111b
#define MAP_llSetRxGain                                    0x113f
#define MAP_llSetT2C1Event1                                0x134f
#define MAP_llSetT2Delta                                   0x1361
#define MAP_llSetT2OVFC1Event1                             0x1355
#define MAP_llSetT2OVFC1Timeout                            0x1349
#define MAP_llSetT2OVFC2Event2                             0x135b
#define MAP_llSetTxPower                                   0x1145
#define MAP_llSetupAdv                                     0x1157
#define MAP_llSetupDirectedAdvEvt                          0x115d
#define MAP_llSetupEncRsp                                  0x1181
#define MAP_llSetupFeatureSetRsp                           0x119f
#define MAP_llSetupNextSlaveEvent                          0x1325
#define MAP_llSetupNonConnectableAdvEvt                    0x1169
#define MAP_llSetupPauseEncRsp                             0x1193
#define MAP_llSetupRejectInd                               0x1199
#define MAP_llSetupScannableAdvEvt                         0x116f
#define MAP_llSetupStartEncReq                             0x1187
#define MAP_llSetupStartEncRsp                             0x118d
#define MAP_llSetupTermInd                                 0x11ab
#define MAP_llSetupUndirectedAdvEvt                        0x1163
#define MAP_llSetupUnknownRsp                              0x11b1
#define MAP_llSetupVersionIndReq                           0x11a5
#define MAP_llSlaveEvt_TaskAbort                           0x131f
#define MAP_llSlaveEvt_TaskEndOk                           0x1319
#define MAP_llStartAdvSetup                                0x1175
#define MAP_llStartSlaveSetup                              0x117b
#define MAP_llStartTimer2                                  0x1343
#define MAP_llStopTimer2                                   0x133d
#define MAP_llUndirectedAdvEvt_TaskEndOk                   0x10fd
#define MAP_llUnexpectedEndCauseHandler                    0x129b
#define MAP_llWriteTxData                                  0x1211
#define MAP_ll_McuPrecisionCount                           0x138b
#define MAP_memset                                         0x689
#define MAP_osalAddTimer                                   0x725
#define MAP_osalDeleteTimer                                0x731
#define MAP_osalFindTimer                                  0x72b
#define MAP_osalInitTasks                                  0x719
#define MAP_osalTimeUpdate                                 0x6ef
#define MAP_osalTimerInit                                  0x71f
#define MAP_osalTimerUpdate                                0x74f
#define MAP_osal_CbTimerInit                               0x959
#define MAP_osal_CbTimerProcessEvent                       0x95f
#define MAP_osal_CbTimerStart                              0x965
#define MAP_osal_CbTimerStop                               0x96b
#define MAP_osal_GetSystemClock                            0x755
#define MAP_osal_bm_adjust_header                          0x94d
#define MAP_osal_bm_alloc                                  0x941
#define MAP_osal_bm_free                                   0x947
#define MAP_osal_clear_event                               0x6cb
#define MAP_osal_get_timeoutEx                             0x749
#define MAP_osal_init_system                               0x6d7
#define MAP_osal_int_disable                               0x6d1
#define MAP_osal_isbufset                                  0x6e9
#define MAP_osal_mem_alloc                                 0x701
#define MAP_osal_mem_free                                  0x707
#define MAP_osal_mem_init                                  0x6f5
#define MAP_osal_mem_kick                                  0x6fb
#define MAP_osal_memcmp                                    0x683
#define MAP_osal_memcpy                                    0x671
#define MAP_osal_memdup                                    0x67d
#define MAP_osal_memset                                    0x689
#define MAP_osal_msg_allocate                              0x695
#define MAP_osal_msg_deallocate                            0x69b
#define MAP_osal_msg_enqueue                               0x6b3
#define MAP_osal_msg_enqueue_push                          0x6a7
#define MAP_osal_msg_extract                               0x6bf
#define MAP_osal_msg_push                                  0x6b9
#define MAP_osal_msg_receive                               0x6ad
#define MAP_osal_msg_send                                  0x6a1
#define MAP_osal_pwrmgr_init                               0x70d
#define MAP_osal_pwrmgr_task_state                         0x713
#define MAP_osal_rand                                      0x68f
#define MAP_osal_revmemcpy                                 0x677
#define MAP_osal_run_system                                0x6e3
#define MAP_osal_set_event                                 0x6c5
#define MAP_osal_snv_init                                  0x9ad
#define MAP_osal_snv_read                                  0x9b9
#define MAP_osal_snv_write                                 0x9b3
#define MAP_osal_start_reload_timer                        0x73d
#define MAP_osal_start_system                              0x6dd
#define MAP_osal_start_timerEx                             0x737
#define MAP_osal_stop_timerEx                              0x743
#define MAP_osal_strlen                                    0x66b
#define MAP_peripheralStateNotificationCB                  0x9fb
#define MAP_phyFindWlEntry                                 0x1451
#define MAP_reportStatusChange                             0x1061
#define MAP_sendAuthEvent                                  0xc23
#define MAP_sendEstLinkEvent                               0xc0b
#define MAP_sendTerminateEvent                             0xc11
#define MAP_setActivePage                                  0x977
#define MAP_simpleProfileChangeCB                          0xa0d
#define MAP_simpleProfile_HandleConnStatusCB               0xa61
#define MAP_simpleProfile_ReadAttrCB                       0xa55
#define MAP_simpleProfile_WriteAttrCB                      0xa5b
#define MAP_smAuthReqToUint8                               0x149f
#define MAP_smDetermineKeySize                             0x1553
#define MAP_smEncrypt                                      0x14ab
#define MAP_smEndPairing                                   0x154d
#define MAP_smFreePairingParams                            0x1547
#define MAP_smGenerateConfirm                              0x1517
#define MAP_smGeneratePairingReqRsp                        0x1511
#define MAP_smGenerateRandBuf                              0x1499
#define MAP_smGenerateRandMsg                              0x151d
#define MAP_smLinkCheck                                    0x14db
#define MAP_smNextPairingState                             0x14f9
#define MAP_smPairingSendEncInfo                           0x1529
#define MAP_smPairingSendIdentityAddrInfo                  0x153b
#define MAP_smPairingSendIdentityInfo                      0x1535
#define MAP_smPairingSendMasterID                          0x152f
#define MAP_smPairingSendSingingInfo                       0x1541
#define MAP_smProcessDataMsg                               0x14e7
#define MAP_smProcessEncryptChange                         0x14f3
#define MAP_smProcessOSALMsg                               0x1595
#define MAP_smProcessPairingReq                            0x1505
#define MAP_smProcessRandComplete                          0x146f
#define MAP_smRegisterResponder                            0x14d5
#define MAP_smResponderProcessLTKReq                       0x1565
#define MAP_smResponderSendNextKeyInfo                     0x1583
#define MAP_smSavePairInfo                                 0x1523
#define MAP_smSendFailAndEnd                               0x14ed
#define MAP_smSendSMMsg                                    0x161f
#define MAP_smSetPairingReqRsp                             0x1559
#define MAP_smStartEncryption                              0x150b
#define MAP_smStartRspTimer                                0x1475
#define MAP_smStopRspTimer                                 0x147b
#define MAP_smTimedOut                                     0x14e1
#define MAP_smUint8ToAuthReq                               0x14a5
#define MAP_sm_CMAC                                        0x14b1
#define MAP_sm_ah                                          0x1481
#define MAP_sm_c1                                          0x14ff
#define MAP_sm_c1new                                       0x1487
#define MAP_sm_s1                                          0x1493
#define MAP_sm_xor                                         0x148d
#define MAP_smpBuildEncInfo                                0x15d7
#define MAP_smpBuildIdentityAddrInfo                       0x15f5
#define MAP_smpBuildIdentityInfo                           0x15ef
#define MAP_smpBuildMasterID                               0x15e3
#define MAP_smpBuildPairingConfirm                         0x15b3
#define MAP_smpBuildPairingFailed                          0x15cb
#define MAP_smpBuildPairingRandom                          0x15bf
#define MAP_smpBuildPairingReq                             0x159b
#define MAP_smpBuildPairingReqRsp                          0x15a7
#define MAP_smpBuildPairingRsp                             0x15a1
#define MAP_smpBuildSecurityReq                            0x1613
#define MAP_smpBuildSigningInfo                            0x1607
#define MAP_smpParseEncInfo                                0x15dd
#define MAP_smpParseIdentityAddrInfo                       0x1601
#define MAP_smpParseIdentityInfo                           0x15fb
#define MAP_smpParseMasterID                               0x15e9
#define MAP_smpParsePairingConfirm                         0x15b9
#define MAP_smpParsePairingFailed                          0x15d1
#define MAP_smpParsePairingRandom                          0x15c5
#define MAP_smpParsePairingReq                             0x15ad
#define MAP_smpParseSecurityReq                            0x1619
#define MAP_smpParseSigningInfo                            0x160d
#define MAP_smpResponderProcessIncoming                    0x156b
#define MAP_smpResponderProcessMasterID                    0x157d
#define MAP_smpResponderProcessPairingRandom               0x1577
#define MAP_smpResponderProcessPairingReq                  0x1571
#define MAP_spiInit                                        0x7f7
#define MAP_spiReadByte                                    0x7f1
#define MAP_spiWriteByte                                   0x7eb
#define MAP_strlen                                         0x66b
#define MAP_uartInit                                       0x7fd
#define MAP_uartWriteByte                                  0x803
#define MAP_uartWriteString                                0x809
#define MAP_verInfo                                        0xd79
#define MAP_verifyWordM                                    0x9a1
#define MAP_writeItem                                      0x995
#define MAP_writeWord                                      0x9a7
#define MAP_xor_128                                        0x14bd
#define MAP_notify                                         0x696
#define MAP_simpleBLEPeripheral_TaskID                     0x7ad
#define MAP_accelEnabler                                   0x494
#define MAP_attDeviceName                                  0xfbb
