#define MAP_ATT_BuildErrorRsp                              0xcd0
#define MAP_ATT_BuildExchangeMTURsp                        0xcdc
#define MAP_ATT_BuildFindByTypeValueRsp                    0xcf4
#define MAP_ATT_BuildFindInfoRsp                           0xce8
#define MAP_ATT_BuildHandleValueInd                        0xd48
#define MAP_ATT_BuildPrepareWriteRsp                       0xd3c
#define MAP_ATT_BuildReadBlobRsp                           0xd1e
#define MAP_ATT_BuildReadByGrpTypeRsp                      0xd30
#define MAP_ATT_BuildReadByTypeRsp                         0xd00
#define MAP_ATT_BuildReadMultiRsp                          0xd2a
#define MAP_ATT_BuildReadRsp                               0xd0c
#define MAP_ATT_CompareUUID                                0xd54
#define MAP_ATT_ConvertUUIDto128                           0xd5a
#define MAP_ATT_ErrorRsp                                   0xc76
#define MAP_ATT_ExchangeMTURsp                             0xc7c
#define MAP_ATT_ExecuteWriteRsp                            0xcb8
#define MAP_ATT_FindByTypeValueRsp                         0xc88
#define MAP_ATT_FindInfoRsp                                0xc82
#define MAP_ATT_HandleValueInd                             0xcc4
#define MAP_ATT_HandleValueNoti                            0xcbe
#define MAP_ATT_ParseExchangeMTUReq                        0xcd6
#define MAP_ATT_ParseExecuteWriteReq                       0xd42
#define MAP_ATT_ParseFindByTypeValueReq                    0xcee
#define MAP_ATT_ParseFindInfoReq                           0xce2
#define MAP_ATT_ParsePacket                                0xcca
#define MAP_ATT_ParsePrepareWriteReq                       0xd36
#define MAP_ATT_ParseReadBlobReq                           0xd18
#define MAP_ATT_ParseReadByTypeReq                         0xcfa
#define MAP_ATT_ParseReadMultiReq                          0xd24
#define MAP_ATT_ParseReadReq                               0xd06
#define MAP_ATT_ParseWriteReq                              0xd12
#define MAP_ATT_PrepareWriteRsp                            0xcb2
#define MAP_ATT_ReadBlobRsp                                0xc9a
#define MAP_ATT_ReadByGrpTypeRsp                           0xca6
#define MAP_ATT_ReadByTypeRsp                              0xc8e
#define MAP_ATT_ReadMultiRsp                               0xca0
#define MAP_ATT_ReadRsp                                    0xc94
#define MAP_ATT_WriteRsp                                   0xcac
#define MAP_Accel_AddService                               0x90a
#define MAP_Accel_GetParameter                             0x91c
#define MAP_Accel_RegisterAppCBs                           0x910
#define MAP_Accel_SetParameter                             0x916
#define MAP_Batt_AddService                                0x934
#define MAP_Batt_Register                                  0x93a
#define MAP_CodeGeneratorStartPoint                        0xc1c
#define MAP_CodeGenerator_EVT_1_CB                         0xbfe
#define MAP_CodeGenerator_EVT_2_CB                         0xc04
#define MAP_CodeGenerator_EVT_3_CB                         0xc0a
#define MAP_CodeGenerator_EVT_4_CB                         0xc10
#define MAP_DevInfo_AddService                             0x952
#define MAP_DevInfo_SetParameter                           0x958
#define MAP_EcoExecProfileChangeCB                         0xbda
#define MAP_EcoExecProfile_AddService                      0x7de
#define MAP_EcoExecProfile_GetParameter                    0x7ea
#define MAP_EcoExecProfile_HandleConnStatusCB              0x7fc
#define MAP_EcoExecProfile_ReadAttrCB                      0x7f0
#define MAP_EcoExecProfile_RegisterAppCBs                  0x7e4
#define MAP_EcoExecProfile_WriteAttrCB                     0x7f6
#define MAP_GAPBondMgr_Init                                0xa48
#define MAP_GAPBondMgr_LinkEst                             0x9dc
#define MAP_GAPBondMgr_ProcessEvent                        0xa4e
#define MAP_GAPBondMgr_ProcessGAPMsg                       0x9fa
#define MAP_GAPBondMgr_Register                            0x9f4
#define MAP_GAPBondMgr_ResolveAddr                         0x9e2
#define MAP_GAPBondMgr_ServiceChangeInd                    0x9e8
#define MAP_GAPBondMgr_SetParameter                        0x9d6
#define MAP_GAPBondMgr_UpdateCharCfg                       0x9ee
#define MAP_GAPRole_GetParameter                           0xb9e
#define MAP_GAPRole_Init                                   0xbb0
#define MAP_GAPRole_ProcessEvent                           0xbb6
#define MAP_GAPRole_SendUpdateParam                        0xbc2
#define MAP_GAPRole_SetParameter                           0xb98
#define MAP_GAPRole_StartDevice                            0xba4
#define MAP_GAPRole_TerminateConnection                    0xbaa
#define MAP_GAP_Authenticate                               0xdf0
#define MAP_GAP_Bond                                       0xe02
#define MAP_GAP_DeviceInit                                 0x9d0
#define MAP_GAP_EndDiscoverable                            0xe68
#define MAP_GAP_GetParamValue                              0xd66
#define MAP_GAP_Init                                       0xeb6
#define MAP_GAP_MakeDiscoverable                           0xe5c
#define MAP_GAP_NumActiveConnections                       0xec2
#define MAP_GAP_ParamsInit                                 0xd6c
#define MAP_GAP_PasscodeUpdate                             0xdfc
#define MAP_GAP_PeriDevMgrInit                             0xe6e
#define MAP_GAP_ProcessEvent                               0xebc
#define MAP_GAP_RegisterForHCIMsgs                         0xeb0
#define MAP_GAP_ResolvePrivateAddr                         0xdcc
#define MAP_GAP_SecParamsInit                              0xd72
#define MAP_GAP_SendSlaveSecurityRequest                   0xeaa
#define MAP_GAP_SetParamValue                              0xd60
#define MAP_GAP_Signable                                   0xdea
#define MAP_GAP_TerminateAuth                              0xdf6
#define MAP_GAP_TerminateLinkReq                           0xde4
#define MAP_GAP_UpdateAdvertisingData                      0xe62
#define MAP_GATTServApp_AddService                         0xfe8
#define MAP_GATTServApp_FindAttr                           0xfe2
#define MAP_GATTServApp_Init                               0xfca
#define MAP_GATTServApp_InitCharCfg                        0x1054
#define MAP_GATTServApp_ProcessCCCWriteReq                 0x1066
#define MAP_GATTServApp_ProcessCharCfg                     0x106c
#define MAP_GATTServApp_ProcessEvent                       0xfd0
#define MAP_GATTServApp_ReadAttr                           0x103c
#define MAP_GATTServApp_ReadCharCfg                        0x105a
#define MAP_GATTServApp_RegisterForMsg                     0xfc4
#define MAP_GATTServApp_RegisterService                    0xfd6
#define MAP_GATTServApp_SendCCCUpdatedEvent                0x1078
#define MAP_GATTServApp_SendServiceChangedInd              0x104e
#define MAP_GATTServApp_UpdateCharCfg                      0x1048
#define MAP_GATTServApp_WriteAttr                          0x1042
#define MAP_GATTServApp_WriteCharCfg                       0x1060
#define MAP_GATT_FindHandle                                0xf22
#define MAP_GATT_FindHandleUUID                            0xf1c
#define MAP_GATT_FindNextAttr                              0xf28
#define MAP_GATT_Indication                                0xf34
#define MAP_GATT_Init                                      0xfa0
#define MAP_GATT_InitServer                                0xef8
#define MAP_GATT_Notification                              0xf3a
#define MAP_GATT_ProcessEvent                              0xfa6
#define MAP_GATT_RegisterForReq                            0xf04
#define MAP_GATT_RegisterService                           0xefe
#define MAP_GATT_ServiceChangedInd                         0xf16
#define MAP_GATT_ServiceNumAttrs                           0xf2e
#define MAP_GATT_VerifyReadPermissions                     0xf0a
#define MAP_GATT_VerifyWritePermissions                    0xf10
#define MAP_GGS_AddService                                 0xee0
#define MAP_GGS_SetParameter                               0xeda
#define MAP_HCI_CommandCompleteEvent                       0x1138
#define MAP_HCI_CommandStatusEvent                         0x1144
#define MAP_HCI_DataBufferOverflowEvent                    0x112c
#define MAP_HCI_DisconnectCmd                              0x108a
#define MAP_HCI_EXT_ClkDivOnHaltCmd                        0x10de
#define MAP_HCI_EXT_DeclareNvUsageCmd                      0x10e4
#define MAP_HCI_GAPTaskRegister                            0x1798
#define MAP_HCI_Init                                       0x178c
#define MAP_HCI_L2CAPTaskRegister                          0x179e
#define MAP_HCI_LE_AddWhiteListCmd                         0x10c6
#define MAP_HCI_LE_ClearWhiteListCmd                       0x10c0
#define MAP_HCI_LE_LtkReqNegReplyCmd                       0x10d8
#define MAP_HCI_LE_LtkReqReplyCmd                          0x10d2
#define MAP_HCI_LE_RandCmd                                 0x10cc
#define MAP_HCI_LE_ReadBufSizeCmd                          0x109c
#define MAP_HCI_LE_SetAdvDataCmd                           0x10ae
#define MAP_HCI_LE_SetAdvEnableCmd                         0x10ba
#define MAP_HCI_LE_SetAdvParamCmd                          0x10a8
#define MAP_HCI_LE_SetRandomAddressCmd                     0x10a2
#define MAP_HCI_LE_SetScanRspDataCmd                       0x10b4
#define MAP_HCI_NumOfCompletedPacketsEvent                 0x1132
#define MAP_HCI_ProcessEvent                               0x1792
#define MAP_HCI_ReadBDADDRCmd                              0x1090
#define MAP_HCI_ReadRssiCmd                                0x1096
#define MAP_HCI_SMPTaskRegister                            0x17a4
#define MAP_HCI_SendCommandCompleteEvent                   0x1150
#define MAP_HCI_SendCommandStatusEvent                     0x114a
#define MAP_HCI_SendControllerToHostEvent                  0x1156
#define MAP_HCI_SendDataPkt                                0x1084
#define MAP_HCI_TxDataBufferInsert                         0x1102
#define MAP_HCI_TxDataSend                                 0x1108
#define MAP_HCI_VendorSpecifcCommandCompleteEvent          0x113e
#define MAP_HCI_bm_alloc                                   0x107e
#define MAP_HalAdcInit                                     0xa78
#define MAP_HalAdcRead                                     0xa7e
#define MAP_HalAdcSetReference                             0xa84
#define MAP_HalAesInit                                     0xa90
#define MAP_HalDmaInit                                     0xa96
#define MAP_HalDriverInit                                  0xaa2
#define MAP_HalFlashErase                                  0xac0
#define MAP_HalFlashRead                                   0xab4
#define MAP_HalFlashWrite                                  0xaba
#define MAP_HalI2CInit                                     0xacc
#define MAP_HalI2CRead                                     0xad2
#define MAP_HalI2CWrite                                    0xad8
#define MAP_HalKeyConfig                                   0xae4
#define MAP_HalKeyInit                                     0xade
#define MAP_HalKeyPoll                                     0xaea
#define MAP_HalLedBlink                                    0xb08
#define MAP_HalLedInit                                     0xafc
#define MAP_HalLedOnOff                                    0xb14
#define MAP_HalLedSet                                      0xb02
#define MAP_HalLedUpdate                                   0xb0e
#define MAP_Hal_Init                                       0xa9c
#define MAP_Hal_ProcessEvent                               0xaa8
#define MAP_Hal_ProcessPoll                                0xaae
#define MAP_InitBoard                                      0x8f2
#define MAP_L2CAP_BuildCmdReject                           0x11e0
#define MAP_L2CAP_CmdReject                                0x1192
#define MAP_L2CAP_ConnParamUpdateReq                       0x1198
#define MAP_L2CAP_Init                                     0x119e
#define MAP_L2CAP_ParseParamUpdateReq                      0x11f2
#define MAP_L2CAP_ProcessEvent                             0x11a4
#define MAP_L2CAP_RegisterApp                              0x1186
#define MAP_L2CAP_SendData                                 0x118c
#define MAP_L2CAP_bm_alloc                                 0x122e
#define MAP_LL_AddWhiteListDevice                          0x129a
#define MAP_LL_ClearWhiteList                              0x1294
#define MAP_LL_ConnActive                                  0x12ee
#define MAP_LL_ConnParamUpdateCback                        0x1168
#define MAP_LL_ConnectionCompleteCback                     0x115c
#define MAP_LL_CtrlToHostFlowControl                       0x12b2
#define MAP_LL_Disconnect                                  0x12be
#define MAP_LL_DisconnectCback                             0x1162
#define MAP_LL_ENC_AES128_Encrypt                          0x1420
#define MAP_LL_ENC_Decrypt                                 0x1450
#define MAP_LL_ENC_DecryptMsg                              0x143e
#define MAP_LL_ENC_Encrypt                                 0x144a
#define MAP_LL_ENC_EncryptMsg                              0x1438
#define MAP_LL_ENC_GenDeviceIV                             0x141a
#define MAP_LL_ENC_GenDeviceSKD                            0x1414
#define MAP_LL_ENC_GenerateMIC                             0x1444
#define MAP_LL_ENC_GeneratePseudoRandNum                   0x1408
#define MAP_LL_ENC_GenerateTrueRandNum                     0x140e
#define MAP_LL_ENC_InitAesDMA                              0x1426
#define MAP_LL_ENC_LoadEmptyIV                             0x1432
#define MAP_LL_ENC_MoveData                                0x142c
#define MAP_LL_ENC_ReverseBytes                            0x1402
#define MAP_LL_EXT_ClkDivOnHalt                            0x12f4
#define MAP_LL_EXT_DeclareNvUsage                          0x12fa
#define MAP_LL_EXT_ExtendRfRangeCback                      0x10fc
#define MAP_LL_EXT_SetRxGainCback                          0x10f0
#define MAP_LL_EXT_SetTxPowerCback                         0x10f6
#define MAP_LL_EncChangeCback                              0x117a
#define MAP_LL_EncKeyRefreshCback                          0x1180
#define MAP_LL_EncLtkNegReply                              0x12e8
#define MAP_LL_EncLtkReply                                 0x12e2
#define MAP_LL_EncLtkReqCback                              0x1174
#define MAP_LL_Encrypt                                     0x12a0
#define MAP_LL_Init                                        0x1276
#define MAP_LL_ProcessEvent                                0x127c
#define MAP_LL_PseudoRand                                  0x12ac
#define MAP_LL_Rand                                        0x12a6
#define MAP_LL_RandCback                                   0x10ea
#define MAP_LL_ReadBDADDR                                  0x1288
#define MAP_LL_ReadRemoteVersionInfoCback                  0x116e
#define MAP_LL_ReadRssi                                    0x12b8
#define MAP_LL_Reset                                       0x1282
#define MAP_LL_RxDataCompleteCback                         0x111a
#define MAP_LL_RxReqDataBufCback                           0x1114
#define MAP_LL_SetAdvControl                               0x12d6
#define MAP_LL_SetAdvData                                  0x12d0
#define MAP_LL_SetAdvParam                                 0x12ca
#define MAP_LL_SetRandomAddress                            0x128e
#define MAP_LL_SetScanRspData                              0x12dc
#define MAP_LL_TxData                                      0x12c4
#define MAP_LL_TxDataCompleteCback                         0x1120
#define MAP_OnBoard_KeyCallback                            0x904
#define MAP_OnBoard_SendKeys                               0x8fe
#define MAP_Onboard_rand                                   0x8f8
#define MAP_PHY_AddWlEntry                                 0x155e
#define MAP_PHY_ClearAllRegsAndFifos                       0x1510
#define MAP_PHY_ClearBlacklist                             0x1576
#define MAP_PHY_ClearBlacklistIndex                        0x1570
#define MAP_PHY_ClearSavedWhiteList                        0x157c
#define MAP_PHY_ClearWhitelist                             0x1558
#define MAP_PHY_CommitRxFifo                               0x15a6
#define MAP_PHY_ConfigWhitener                             0x1594
#define MAP_PHY_ConfigureAppendRfStatus                    0x1588
#define MAP_PHY_ConfigureFifoDataProcessing                0x1582
#define MAP_PHY_ConfigureMD                                0x153a
#define MAP_PHY_DeallocateRxFifo                           0x15ac
#define MAP_PHY_GetAdvChans                                0x1528
#define MAP_PHY_GetEndCause                                0x1540
#define MAP_PHY_Init                                       0x1504
#define MAP_PHY_InitSeqStat                                0x1546
#define MAP_PHY_Reset                                      0x150a
#define MAP_PHY_RetryRxFifo                                0x15a0
#define MAP_PHY_RetryTxFifo                                0x159a
#define MAP_PHY_SetAdvChans                                0x152e
#define MAP_PHY_SetAdvWlPolicy                             0x1564
#define MAP_PHY_SetBlacklistIndex                          0x156a
#define MAP_PHY_SetCRCInit                                 0x1522
#define MAP_PHY_SetEndConnection                           0x1534
#define MAP_PHY_SetFifoConfig                              0x158e
#define MAP_PHY_SetMaxNack                                 0x1552
#define MAP_PHY_SetOwnAddr                                 0x1516
#define MAP_PHY_SetPeerAddr                                0x151c
#define MAP_PHY_SetRfFreq                                  0x15b2
#define MAP_PHY_SetSyncWord                                0x154c
#define MAP_SM_CalcRandomAddr                              0x15be
#define MAP_SM_GenerateAuthenSig                           0x15ca
#define MAP_SM_Init                                        0x16f0
#define MAP_SM_PasskeyUpdate                               0x1636
#define MAP_SM_ProcessEvent                                0x16f6
#define MAP_SM_ResolveRandomAddrs                          0x15c4
#define MAP_SM_ResponderInit                               0x16c6
#define MAP_SM_StartPairing                                0x1630
#define MAP_SM_VerifyAuthenSig                             0x15d0
#define MAP_SimpleBLEPeripheral_Init                       0xbc8
#define MAP_SimpleBLEPeripheral_ProcessEvent               0xbce
#define MAP_SimpleProfile_AddService                       0xc22
#define MAP_SimpleProfile_GetParameter                     0xc34
#define MAP_SimpleProfile_RegisterAppCBs                   0xc28
#define MAP_SimpleProfile_SetParameter                     0xc2e
#define MAP_accInit                                        0x964
#define MAP_accReadAcc                                     0x976
#define MAP_accReadReg                                     0x970
#define MAP_accSetFreeFallEvent                            0x97c
#define MAP_accWriteReg                                    0x96a
#define MAP_accelEnablerChangeCB                           0xbf2
#define MAP_accelRead                                      0xbe0
#define MAP_accel_HandleConnStatusCB                       0x92e
#define MAP_accel_ReadAttrCB                               0x922
#define MAP_accel_WriteAttrCB                              0x928
#define MAP_aesDmaInit                                     0xa8a
#define MAP_attSendMsg                                     0xd4e
#define MAP_battMeasure                                    0x94c
#define MAP_battProfileChangeCB                            0xbf8
#define MAP_battReadAttrCB                                 0x940
#define MAP_battWriteAttrCB                                0x946
#define MAP_bm_desc_from_payload                           0xb2c
#define MAP_cleanErasedPage                                0xb5c
#define MAP_compactPage                                    0xb74
#define MAP_devInfo_ReadAttrCB                             0x95e
#define MAP_disconnectNext                                 0xe2c
#define MAP_erasePage                                      0xb56
#define MAP_findItem                                       0xb68
#define MAP_findOffset                                     0xb62
#define MAP_gapAddAddrAdj                                  0xd8a
#define MAP_gapBondMgrAddBond                              0xa18
#define MAP_gapBondMgrAuthenticate                         0xa60
#define MAP_gapBondMgrBondReq                              0xa66
#define MAP_gapBondMgrBondTotal                            0xa36
#define MAP_gapBondMgrChangeState                          0xa00
#define MAP_gapBondMgrEraseAllBondings                     0xa3c
#define MAP_gapBondMgrEraseBonding                         0xa42
#define MAP_gapBondMgrFindAddr                             0xa24
#define MAP_gapBondMgrFindCharCfgItem                      0xa0c
#define MAP_gapBondMgrGetPublicAddr                        0xa1e
#define MAP_gapBondMgrInvertCharCfgItem                    0xa12
#define MAP_gapBondMgrReadBonds                            0xa30
#define MAP_gapBondMgrResolvePrivateAddr                   0xa2a
#define MAP_gapBondMgrSendServiceChange                    0xa54
#define MAP_gapBondMgrUpdateCharCfg                        0xa06
#define MAP_gapBondMgr_SyncCharCfg                         0xa72
#define MAP_gapBondMgr_SyncWhiteList                       0xa6c
#define MAP_gapBondSetupPrivFlag                           0xa5a
#define MAP_gapDetermineAddrType                           0xd90
#define MAP_gapFindADType                                  0xdde
#define MAP_gapFreeAdvertState                             0xe9e
#define MAP_gapFreeAuthLink                                0xe38
#define MAP_gapFreeEstLink                                 0xe3e
#define MAP_gapGetDevAddress                               0xdba
#define MAP_gapGetDevAddressMode                           0xdb4
#define MAP_gapGetIRK                                      0xdc0
#define MAP_gapGetSRK                                      0xd9c
#define MAP_gapGetSignCounter                              0xda2
#define MAP_gapIncSignCounter                              0xda8
#define MAP_gapIsAdvertising                               0xdd2
#define MAP_gapPairingCompleteCB                           0xe56
#define MAP_gapPasskeyNeededCB                             0xe50
#define MAP_gapPeriProcessHCICmdCompleteEvt                0xe74
#define MAP_gapProcessAdvertisingEvt                       0xe92
#define MAP_gapProcessConnUpdateCompleteEvt                0xe0e
#define MAP_gapProcessConnectionCompleteEvt                0xe08
#define MAP_gapProcessDisconnectCompleteEvt                0xe14
#define MAP_gapProcessHCICmdCompleteEvt                    0xece
#define MAP_gapProcessNewAddr                              0xd84
#define MAP_gapProcessOSALMsg                              0xec8
#define MAP_gapProcessRandomAddrComplete                   0xd96
#define MAP_gapReadBD_ADDRStatus                           0xd78
#define MAP_gapReadBufSizeCmdStatus                        0xd7e
#define MAP_gapRegisterPeripheral                          0xed4
#define MAP_gapRole_ProcessGAPMsg                          0xbbc
#define MAP_gapSendBondCompleteEvent                       0xe44
#define MAP_gapSendDeviceInitDoneEvent                     0xdc6
#define MAP_gapSendLinkUpdateEvent                         0xe26
#define MAP_gapSendMakeDiscEvent                           0xe98
#define MAP_gapSendPairingReqEvent                         0xe4a
#define MAP_gapSetAdvParams                                0xe7a
#define MAP_gapSetAdvParamsStatus                          0xe80
#define MAP_gapUpdateConnSignCounter                       0xdae
#define MAP_gapValidADType                                 0xdd8
#define MAP_gapWriteAdvDataStatus                          0xe8c
#define MAP_gapWriteAdvEnableStatus                        0xe86
#define MAP_gattFindServerInfo                             0xf88
#define MAP_gattGetServerStatus                            0xf82
#define MAP_gattNotifyEvent                                0xfb2
#define MAP_gattProcessExchangeMTUReq                      0xf4c
#define MAP_gattProcessExecuteWriteReq                     0xf7c
#define MAP_gattProcessFindByTypeValueReq                  0xf58
#define MAP_gattProcessFindInfoReq                         0xf52
#define MAP_gattProcessReadByGrpTypeReq                    0xf70
#define MAP_gattProcessReadByTypeReq                       0xf5e
#define MAP_gattProcessReadMultiReq                        0xf6a
#define MAP_gattProcessReadReq                             0xf64
#define MAP_gattProcessRxData                              0xfac
#define MAP_gattProcessWriteReq                            0xf76
#define MAP_gattRegisterServer                             0xf9a
#define MAP_gattServApp_FindAuthorizeAttrCB                0x1030
#define MAP_gattServApp_FindCharCfgItem                    0x102a
#define MAP_gattServApp_FindPrepareWriteQ                  0x1024
#define MAP_gattServApp_FindServiceCBs                     0xfee
#define MAP_gattServApp_HandleConnStatusCB                 0x1072
#define MAP_gattServApp_ProcessExecuteWriteReq             0x101e
#define MAP_gattServApp_ProcessFindByTypeValueReq          0xffa
#define MAP_gattServApp_ProcessMsg                         0xff4
#define MAP_gattServApp_ProcessPrepareWriteReq             0x1018
#define MAP_gattServApp_ProcessReadByGrpTypeReq            0x100c
#define MAP_gattServApp_ProcessReadByTypeReq               0x1000
#define MAP_gattServApp_ProcessReadMultiReq                0x1006
#define MAP_gattServApp_ProcessWriteReq                    0x1012
#define MAP_gattServApp_SetNumPrepareWrites                0xfdc
#define MAP_gattServApp_WriteAttrCB                        0x1036
#define MAP_gattServerHandleConnStatusCB                   0xf94
#define MAP_gattServerHandleTimerCB                        0xf8e
#define MAP_gattServerProcessMsgCB                         0xf46
#define MAP_gattServiceLastHandle                          0xf40
#define MAP_gattStartTimer                                 0xfb8
#define MAP_gattStopTimer                                  0xfbe
#define MAP_generate_subkey                                0x161e
#define MAP_ggs_ReadAttrCB                                 0xeec
#define MAP_ggs_SetAttrWPermit                             0xee6
#define MAP_ggs_WriteAttrCB                                0xef2
#define MAP_halGetJoyKeyInput                              0xaf0
#define MAP_halProcessAlarmInterrupt                       0x7d2
#define MAP_halProcessFreeFallInterrupt                    0x7d8
#define MAP_halProcessKeyInterrupt                         0xaf6
#define MAP_hciInitEventMasks                              0x1126
#define MAP_hciTxDataBufferReset                           0x110e
#define MAP_i2cMstStrt                                     0xac6
#define MAP_initNV                                         0xb4a
#define MAP_isLimitedDiscoverableMode                      0xea4
#define MAP_l2capAllocChannel                              0x120a
#define MAP_l2capBuildParamUpdateReq                       0x11ec
#define MAP_l2capEncapSendData                             0x11d4
#define MAP_l2capFindLocalId                               0x1216
#define MAP_l2capFreeChannel                               0x1210
#define MAP_l2capHandleRxError                             0x1228
#define MAP_l2capHandleTimerCB                             0x1222
#define MAP_l2capNotifyData                                0x11fe
#define MAP_l2capNotifySignal                              0x1204
#define MAP_l2capParseCmdReject                            0x11e6
#define MAP_l2capParsePacket                               0x11da
#define MAP_l2capParseParamUpdateRsp                       0x11f8
#define MAP_l2capParseSignalHdr                            0x11c2
#define MAP_l2capProcessReq                                0x11bc
#define MAP_l2capProcessRsp                                0x11b6
#define MAP_l2capProcessRxData                             0x11aa
#define MAP_l2capProcessSignal                             0x11b0
#define MAP_l2capSendCmd                                   0x11ce
#define MAP_l2capSendReq                                   0x11c8
#define MAP_l2capStopTimer                                 0x121c
#define MAP_leftshift_onebit                               0x162a
#define MAP_linkDB_Add                                     0x1240
#define MAP_linkDB_Authen                                  0x1264
#define MAP_linkDB_Find                                    0x124c
#define MAP_linkDB_FindFirst                               0x1252
#define MAP_linkDB_Init                                    0x1234
#define MAP_linkDB_NumActive                               0x125e
#define MAP_linkDB_PerformFunc                             0x126a
#define MAP_linkDB_Register                                0x123a
#define MAP_linkDB_Remove                                  0x1246
#define MAP_linkDB_State                                   0x1258
#define MAP_llAdjustForMissedEvent                         0x13ea
#define MAP_llAdvEvt_TaskAbort                             0x131e
#define MAP_llAdvEvt_TaskConnect                           0x1306
#define MAP_llAllocConnId                                  0x13ba
#define MAP_llAllocTask                                    0x1474
#define MAP_llClearSetInts                                 0x132a
#define MAP_llConnCleanup                                  0x13cc
#define MAP_llConnTerminate                                0x13d2
#define MAP_llConvertCtrlProcTimeoutToEvent                0x13e4
#define MAP_llConvertLstoToEvent                           0x13de
#define MAP_llDequeueCtrlPkt                               0x13a8
#define MAP_llDirectedAdvEvt_TaskEndOk                     0x1300
#define MAP_llDisableT2E1                                  0x14ec
#define MAP_llDisableT2Ints                                0x14e0
#define MAP_llDisableT2IntsEvts                            0x14e6
#define MAP_llDiscoverableAdvEvt_TaskEndOk                 0x1312
#define MAP_llEnqueueCtrlPkt                               0x13a2
#define MAP_llExtendRfRange                                0x133c
#define MAP_llFindNextSecTask                              0x146e
#define MAP_llFindTxPowerSettings                          0x1336
#define MAP_llFreeTask                                     0x147a
#define MAP_llGetActiveTasks                               0x148c
#define MAP_llGetCurrentTask                               0x1480
#define MAP_llGetCurrentTime                               0x14f8
#define MAP_llGetNextConn                                  0x13c6
#define MAP_llGetNumTasks                                  0x1492
#define MAP_llGetTaskState                                 0x1486
#define MAP_llGetTimer2Capture                             0x14f2
#define MAP_llInitFeatureSet                               0x13d8
#define MAP_llInitTimer2                                   0x14c2
#define MAP_llMemCopySrc                                   0x13fc
#define MAP_llNonConnAdvEvt_TaskEndOk                      0x1318
#define MAP_llProcessChanMap                               0x13b4
#define MAP_llProcessPendingTxData                         0x13f0
#define MAP_llProcessPostRfOps                             0x1330
#define MAP_llProcessSlaveControlProcedures                0x14bc
#define MAP_llReleaseAllConnId                             0x13c0
#define MAP_llReplaceCtrlPkt                               0x13ae
#define MAP_llRestoreConnState                             0x14a4
#define MAP_llRfInit                                       0x1324
#define MAP_llSave_rxFIFO                                  0x149e
#define MAP_llSave_txFIFO                                  0x1498
#define MAP_llScheduleTask                                 0x1468
#define MAP_llScheduler                                    0x1462
#define MAP_llSchedulerInit                                0x145c
#define MAP_llSetT2C1Event1                                0x14ce
#define MAP_llSetT2LongC1Event1                            0x14d4
#define MAP_llSetT2LongC1Timeout                           0x14c8
#define MAP_llSetT2OVFC2Event2                             0x14da
#define MAP_llSetupAdv                                     0x1342
#define MAP_llSetupDirectedAdvEvt                          0x1348
#define MAP_llSetupEncRsp                                  0x136c
#define MAP_llSetupFeatureSetRsp                           0x138a
#define MAP_llSetupNextSlaveEvent                          0x14b6
#define MAP_llSetupNonConnectableAdvEvt                    0x1354
#define MAP_llSetupPauseEncRsp                             0x137e
#define MAP_llSetupRejectInd                               0x1384
#define MAP_llSetupScannableAdvEvt                         0x135a
#define MAP_llSetupStartEncReq                             0x1372
#define MAP_llSetupStartEncRsp                             0x1378
#define MAP_llSetupTermInd                                 0x1396
#define MAP_llSetupUndirectedAdvEvt                        0x134e
#define MAP_llSetupUnknownRsp                              0x139c
#define MAP_llSetupVersionIndReq                           0x1390
#define MAP_llSlaveEvt_TaskAbort                           0x14b0
#define MAP_llSlaveEvt_TaskEndOk                           0x14aa
#define MAP_llStartAdvSetup                                0x1360
#define MAP_llStartSlaveSetup                              0x1366
#define MAP_llUndirectedAdvEvt_TaskEndOk                   0x130c
#define MAP_llUnexpectedEndCauseHandler                    0x1456
#define MAP_llWriteTxData                                  0x13f6
#define MAP_ll_McuPrecisionCount                           0x14fe
#define MAP_memset                                         0x820
#define MAP_osalAddTimer                                   0x8bc
#define MAP_osalDeleteTimer                                0x8c8
#define MAP_osalFindTimer                                  0x8c2
#define MAP_osalInitTasks                                  0x8b0
#define MAP_osalTimeUpdate                                 0x886
#define MAP_osalTimerInit                                  0x8b6
#define MAP_osalTimerUpdate                                0x8e6
#define MAP_osal_CbTimerInit                               0xb32
#define MAP_osal_CbTimerProcessEvent                       0xb38
#define MAP_osal_CbTimerStart                              0xb3e
#define MAP_osal_CbTimerStop                               0xb44
#define MAP_osal_GetSystemClock                            0x8ec
#define MAP_osal_bm_adjust_header                          0xb26
#define MAP_osal_bm_alloc                                  0xb1a
#define MAP_osal_bm_free                                   0xb20
#define MAP_osal_clear_event                               0x862
#define MAP_osal_get_timeoutEx                             0x8e0
#define MAP_osal_init_system                               0x86e
#define MAP_osal_int_disable                               0x868
#define MAP_osal_isbufset                                  0x880
#define MAP_osal_mem_alloc                                 0x898
#define MAP_osal_mem_free                                  0x89e
#define MAP_osal_mem_init                                  0x88c
#define MAP_osal_mem_kick                                  0x892
#define MAP_osal_memcmp                                    0x81a
#define MAP_osal_memcpy                                    0x808
#define MAP_osal_memdup                                    0x814
#define MAP_osal_memset                                    0x820
#define MAP_osal_msg_allocate                              0x82c
#define MAP_osal_msg_deallocate                            0x832
#define MAP_osal_msg_enqueue                               0x84a
#define MAP_osal_msg_enqueue_push                          0x83e
#define MAP_osal_msg_extract                               0x856
#define MAP_osal_msg_push                                  0x850
#define MAP_osal_msg_receive                               0x844
#define MAP_osal_msg_send                                  0x838
#define MAP_osal_pwrmgr_init                               0x8a4
#define MAP_osal_pwrmgr_task_state                         0x8aa
#define MAP_osal_rand                                      0x826
#define MAP_osal_revmemcpy                                 0x80e
#define MAP_osal_run_system                                0x87a
#define MAP_osal_set_event                                 0x85c
#define MAP_osal_snv_init                                  0xb86
#define MAP_osal_snv_read                                  0xb92
#define MAP_osal_snv_write                                 0xb8c
#define MAP_osal_start_reload_timer                        0x8d4
#define MAP_osal_start_system                              0x874
#define MAP_osal_start_timerEx                             0x8ce
#define MAP_osal_stop_timerEx                              0x8da
#define MAP_osal_strlen                                    0x802
#define MAP_peripheralStateNotificationCB                  0xbd4
#define MAP_phyFindWlEntry                                 0x15b8
#define MAP_reportStatusChange                             0x1270
#define MAP_rtcGetAlarm                                    0x9ca
#define MAP_rtcGetDate                                     0x9be
#define MAP_rtcGetTime                                     0x9b2
#define MAP_rtcInit                                        0x9a6
#define MAP_rtcSetAlarm                                    0x9c4
#define MAP_rtcSetDate                                     0x9b8
#define MAP_rtcSetTime                                     0x9ac
#define MAP_sendAuthEvent                                  0xe32
#define MAP_sendEstLinkEvent                               0xe1a
#define MAP_sendTerminateEvent                             0xe20
#define MAP_setActivePage                                  0xb50
#define MAP_simpleProfileChangeCB                          0xbec
#define MAP_simpleProfile_HandleConnStatusCB               0xc46
#define MAP_simpleProfile_ReadAttrCB                       0xc3a
#define MAP_simpleProfile_WriteAttrCB                      0xc40
#define MAP_smAuthReqToUint8                               0x1606
#define MAP_smDetermineKeySize                             0x16ba
#define MAP_smEncrypt                                      0x1612
#define MAP_smEndPairing                                   0x16b4
#define MAP_smFreePairingParams                            0x16ae
#define MAP_smGenerateConfirm                              0x167e
#define MAP_smGeneratePairingReqRsp                        0x1678
#define MAP_smGenerateRandBuf                              0x1600
#define MAP_smGenerateRandMsg                              0x1684
#define MAP_smLinkCheck                                    0x1642
#define MAP_smNextPairingState                             0x1660
#define MAP_smPairingSendEncInfo                           0x1690
#define MAP_smPairingSendIdentityAddrInfo                  0x16a2
#define MAP_smPairingSendIdentityInfo                      0x169c
#define MAP_smPairingSendMasterID                          0x1696
#define MAP_smPairingSendSingingInfo                       0x16a8
#define MAP_smProcessDataMsg                               0x164e
#define MAP_smProcessEncryptChange                         0x165a
#define MAP_smProcessOSALMsg                               0x16fc
#define MAP_smProcessPairingReq                            0x166c
#define MAP_smProcessRandComplete                          0x15d6
#define MAP_smRegisterResponder                            0x163c
#define MAP_smResponderProcessLTKReq                       0x16cc
#define MAP_smResponderSendNextKeyInfo                     0x16ea
#define MAP_smSavePairInfo                                 0x168a
#define MAP_smSendFailAndEnd                               0x1654
#define MAP_smSendSMMsg                                    0x1786
#define MAP_smSetPairingReqRsp                             0x16c0
#define MAP_smStartEncryption                              0x1672
#define MAP_smStartRspTimer                                0x15dc
#define MAP_smStopRspTimer                                 0x15e2
#define MAP_smTimedOut                                     0x1648
#define MAP_smUint8ToAuthReq                               0x160c
#define MAP_sm_CMAC                                        0x1618
#define MAP_sm_ah                                          0x15e8
#define MAP_sm_c1                                          0x1666
#define MAP_sm_c1new                                       0x15ee
#define MAP_sm_s1                                          0x15fa
#define MAP_sm_xor                                         0x15f4
#define MAP_smpBuildEncInfo                                0x173e
#define MAP_smpBuildIdentityAddrInfo                       0x175c
#define MAP_smpBuildIdentityInfo                           0x1756
#define MAP_smpBuildMasterID                               0x174a
#define MAP_smpBuildPairingConfirm                         0x171a
#define MAP_smpBuildPairingFailed                          0x1732
#define MAP_smpBuildPairingRandom                          0x1726
#define MAP_smpBuildPairingReq                             0x1702
#define MAP_smpBuildPairingReqRsp                          0x170e
#define MAP_smpBuildPairingRsp                             0x1708
#define MAP_smpBuildSecurityReq                            0x177a
#define MAP_smpBuildSigningInfo                            0x176e
#define MAP_smpParseEncInfo                                0x1744
#define MAP_smpParseIdentityAddrInfo                       0x1768
#define MAP_smpParseIdentityInfo                           0x1762
#define MAP_smpParseMasterID                               0x1750
#define MAP_smpParsePairingConfirm                         0x1720
#define MAP_smpParsePairingFailed                          0x1738
#define MAP_smpParsePairingRandom                          0x172c
#define MAP_smpParsePairingReq                             0x1714
#define MAP_smpParseSecurityReq                            0x1780
#define MAP_smpParseSigningInfo                            0x1774
#define MAP_smpResponderProcessIncoming                    0x16d2
#define MAP_smpResponderProcessMasterID                    0x16e4
#define MAP_smpResponderProcessPairingRandom               0x16de
#define MAP_smpResponderProcessPairingReq                  0x16d8
#define MAP_spiInit                                        0x98e
#define MAP_spiReadByte                                    0x988
#define MAP_spiWriteByte                                   0x982
#define MAP_strlen                                         0x802
#define MAP_timeRead                                       0xbe6
#define MAP_timeserviceChangeCB                            0xc16
#define MAP_timeservice_AddService                         0xc4c
#define MAP_timeservice_GetParameter                       0xc5e
#define MAP_timeservice_HandleConnStatusCB                 0xc70
#define MAP_timeservice_ReadAttrCB                         0xc64
#define MAP_timeservice_RegisterAppCBs                     0xc52
#define MAP_timeservice_SetParameter                       0xc58
#define MAP_timeservice_WriteAttrCB                        0xc6a
#define MAP_uartInit                                       0x994
#define MAP_uartWriteByte                                  0x99a
#define MAP_uartWriteString                                0x9a0
#define MAP_verInfo                                        0xf88
#define MAP_verifyWordM                                    0xb7a
#define MAP_writeItem                                      0xb6e
#define MAP_writeWord                                      0xb80
#define MAP_xor_128                                        0x1624
#define MAP_notify                                         0xea6
#define MAP_simpleBLEPeripheral_TaskID                     0xfbd
#define MAP_accelEnabler                                   0xc95
#define MAP_attDeviceName                                  0x17dd
#define MAP_timeEnabler                                    0xc96
